# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KS_drawing_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(383, 404)
        self.RZ = QtWidgets.QFrame(Dialog)
        self.RZ.setGeometry(QtCore.QRect(20, 10, 161, 251))
        self.RZ.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RZ.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RZ.setObjectName("RZ")
        self.IEC_A = QtWidgets.QRadioButton(self.RZ)
        self.IEC_A.setGeometry(QtCore.QRect(20, 50, 82, 17))
        self.IEC_A.setObjectName("IEC_A")
        self.IEC_B = QtWidgets.QRadioButton(self.RZ)
        self.IEC_B.setGeometry(QtCore.QRect(20, 70, 82, 17))
        self.IEC_B.setObjectName("IEC_B")
        self.IEC_C = QtWidgets.QRadioButton(self.RZ)
        self.IEC_C.setGeometry(QtCore.QRect(20, 90, 82, 17))
        self.IEC_C.setObjectName("IEC_C")
        self.label = QtWidgets.QLabel(self.RZ)
        self.label.setGeometry(QtCore.QRect(20, 10, 91, 16))
        self.label.setObjectName("label")
        self.Imtz_edit = QtWidgets.QLineEdit(self.RZ)
        self.Imtz_edit.setGeometry(QtCore.QRect(20, 120, 51, 20))
        self.Imtz_edit.setObjectName("Imtz_edit")
        self.label_2 = QtWidgets.QLabel(self.RZ)
        self.label_2.setGeometry(QtCore.QRect(80, 120, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.RZ)
        self.label_3.setGeometry(QtCore.QRect(80, 150, 91, 16))
        self.label_3.setObjectName("label_3")
        self.TMS_edit = QtWidgets.QLineEdit(self.RZ)
        self.TMS_edit.setGeometry(QtCore.QRect(20, 150, 51, 20))
        self.TMS_edit.setObjectName("TMS_edit")
        self.label_4 = QtWidgets.QLabel(self.RZ)
        self.label_4.setGeometry(QtCore.QRect(80, 180, 91, 16))
        self.label_4.setObjectName("label_4")
        self.Tto_edit = QtWidgets.QLineEdit(self.RZ)
        self.Tto_edit.setGeometry(QtCore.QRect(20, 210, 51, 20))
        self.Tto_edit.setObjectName("Tto_edit")
        self.label_5 = QtWidgets.QLabel(self.RZ)
        self.label_5.setGeometry(QtCore.QRect(80, 210, 91, 16))
        self.label_5.setObjectName("label_5")
        self.Ito_edit = QtWidgets.QLineEdit(self.RZ)
        self.Ito_edit.setGeometry(QtCore.QRect(20, 180, 51, 20))
        self.Ito_edit.setObjectName("Ito_edit")
        self.radioButton_4 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_4.setGeometry(QtCore.QRect(220, 10, 82, 17))
        self.radioButton_4.setObjectName("radioButton_4")
        self.drawing_btn = QtWidgets.QPushButton(Dialog)
        self.drawing_btn.setGeometry(QtCore.QRect(150, 280, 75, 23))
        self.drawing_btn.setObjectName("drawing_btn")
        self.brows = QtWidgets.QPushButton(Dialog)
        self.brows.setGeometry(QtCore.QRect(10, 330, 75, 23))
        self.brows.setObjectName("brows")
        self.filename = QtWidgets.QLineEdit(Dialog)
        self.filename.setGeometry(QtCore.QRect(90, 330, 281, 23))
        self.filename.setObjectName("filename")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.IEC_A.setText(_translate("Dialog", "IEC/A"))
        self.IEC_B.setText(_translate("Dialog", "IEC/B"))
        self.IEC_C.setText(_translate("Dialog", "IEC/C"))
        self.label.setText(_translate("Dialog", "Тип кривой МТЗ:"))
        self.label_2.setText(_translate("Dialog", "I>"))
        self.label_3.setText(_translate("Dialog", "TMS"))
        self.label_4.setText(_translate("Dialog", "I>>"))
        self.label_5.setText(_translate("Dialog", "T>>"))
        self.radioButton_4.setText(_translate("Dialog", "RadioButton"))
        self.drawing_btn.setText(_translate("Dialog", "Построить"))
        self.brows.setText(_translate("Dialog", "Выбор"))
